language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo
env:
  - TEST_DIR=websocketd
  - TEST_DIR=logic
  - TEST_DIR=fa
script:
  - cd $TEST_DIR && cargo build --verbose --all && cargo test --verbose --all
