name:                binary-demo
version:             0.1.0.0
github:              "githubuser/binary"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/githubuser/binary#readme>

dependencies:
- base >= 4.7 && < 5
- binary >= 0.8
- bytestring >= 0.10
- zlib >= 0.6
- aeson >= 1.4

library:
  source-dirs: src

executables:
  binary-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - binary

tests:
  binary-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - binary
