[package]
name = "websocketd"
version = "0.1.0"
authors = ["_rika <i@ksqsf.moe>"]

[dependencies]
tokio = "1.8.4"
futures = "0.1.23"
failure = "0.1.2"
sha1 = "0.6.0"
base64 = "0.9.2"
bytes = "0.4.9"
failure_derive = "0.1.2"
tokio-process = "0.2.2"
log = "0.4.4"
env_logger = "0.5.13"
